name: Go

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and release
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.12

      - name: Build
        run: |
          go get -v golang.org/x/tools/gopls@$env:GOPLS_VERSION
          $dir = Get-Location
          cd $env:USERPROFILE\go\bin
          &"c:\Program Files\7-Zip\7z.exe" a $dir\gopls-$env:GOPLS_VERSION.7z gopls.exe

          cd $dir
          $hash = (Get-FileHash -Algorithm SHA256 gopls-$env:GOPLS_VERSION.7z).Hash
          "$hash  gopls-$env:GOPLS_VERSION.7z" | Out-File -Encoding ascii -File sha256sum.txt
        env:
          GO111MODULE: on
          GOPLS_VERSION: v0.5.5

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            gopls v0.5.5 binary for Windows 64-bit.
          draft: false
          prerelease: false

      - name: Upload Release archive
        id: upload-release-binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./gopls-v0.5.5.7z
          asset_name: gopls-v0.5.5.7z
          asset_content_type: application/octet-stream

      - name: Upload Release checksum
        id: upload-release-checksum
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sha256sum.txt
          asset_name: sha256sum.txt
          asset_content_type: text/plain
