name: Go

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'

jobs:
  build:
    name: Build and release
    runs-on: ubuntu-latest
    env:
      GOPLS_VERSION: v0.19.0
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.24

      - name: Build
        run: |
          go install -v golang.org/x/tools/gopls@$GOPLS_VERSION
          $dir = pwd
          cd $PATH\go\bin
          & tar -czvf $dir\gopls.tar.gz gopls
        env:
          GO111MODULE: on

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: gopls.tar.gz
